# Generated by Django 5.0.3 on 2025-02-03 03:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryView',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('shop.category',),
        ),
        migrations.AlterField(
            model_name='product',
            name='Lcategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_L', to='shop.category'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Scategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products_S', to='shop.category'),
        ),
    ]
